version: "3.5"

services:
    auth:
        container_name: auth-api
        image: node:14
        volumes:
        - "./auth:/src"
        working_dir: '/src'
        environment:
            LOCAL_DYNAMODB: 'http://local-dynamodb:8000'
            NODE_ENV: local
            PORT: 8001
        ports:
        - "8301:8001"
        command: bash -c "npm install && /src/node_modules/nodemon/bin/nodemon.js  --config nodemon.json server.ts"

    stations:
        container_name: stations-api
        image: node:14
        volumes:
        - "./stations:/src"
        working_dir: '/src'
        environment:
            LOCAL_DYNAMODB: 'http://local-dynamodb:8000'
            NODE_ENV: local
            PORT: 8002
        ports:
        - "8302:8002"
        command: bash -c "npm install && /src/node_modules/nodemon/bin/nodemon.js  --config nodemon.json server.ts"

    nginx:
        container_name: webserver
        image: nginx:1.21.0-alpine
        depends_on:
            - auth
            - stations
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "8378:80"

networks:
    default:
        external:
            name: local-dynamodb
volumes:
    dynamodata: {}
