version: "3.5"

services:
  dynamo:
    container_name: local-dynamodb
    image: amazon/dynamodb-local
    networks:
      - local-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/usr/local/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
  aws:
    container_name: aws-cli
    image: amazon/aws-cli
    depends_on:
      - "dynamo"
    environment:
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local

    networks:
      - local-dynamodb
    command: 'dynamodb create-table --endpoint-url http://dynamo:8000 
    --region ap-northeast-1
    --table-name vacan-dev-database 
    --attribute-definitions 
        AttributeName="hk",AttributeType="S" 
        AttributeName="sk",AttributeType="S" 
        AttributeName="hk2",AttributeType="S" 
        AttributeName="sk2",AttributeType="S" 
    --key-schema AttributeName="hk",KeyType="HASH" AttributeName="sk",KeyType="RANGE" 
    --provisioned-throughput ReadCapacityUnits=10,WriteCapacityUnits=5 
    --global-secondary-indexes 
        "[
            {
                \"IndexName\": \"gsi1\",
                \"KeySchema\": [
                    {\"AttributeName\": \"hk2\",\"KeyType\":\"HASH\"},
                    {\"AttributeName\": \"sk\",\"KeyType\":\"RANGE\"}
                ],
                \"Projection\": {
                    \"ProjectionType\": \"ALL\"
                },
                \"ProvisionedThroughput\": {
                    \"ReadCapacityUnits\": 10,
                    \"WriteCapacityUnits\": 5
                }
            },
            {
                \"IndexName\": \"gsi2\",
                \"KeySchema\": [
                    {\"AttributeName\": \"hk\",\"KeyType\":\"HASH\"},
                    {\"AttributeName\": \"sk2\",\"KeyType\":\"RANGE\"}
                ],
                \"Projection\": {
                    \"ProjectionType\": \"ALL\"
                },
                \"ProvisionedThroughput\": {
                    \"ReadCapacityUnits\": 10,
                    \"WriteCapacityUnits\": 5
                }
            }
        ]"'

networks:
  local-dynamodb:
    name: local-dynamodb

volumes:
  dynamodata: {}
