component: aws-iam-role
name: permissions
provider:
  useDotEnv: true

inputs:
  name: ${app}-${stage}-${name}
  region: ${env:region}
  service: lambda.amazonaws.com
  policy:
    # AWS Lambda function containing Express Logs and Assume Role access
    - Effect: Allow
      Action:
        - sts:AssumeRole
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"
    # AWS DynamoDB Table access
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:UpdateTable
        - dynamodb:DeleteItem
      Resource:
        - ${output:database.arn}
        - ${output:database.arn}/index/*
