name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-1                  # set this to your preferred AWS region, e.g. us-west-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build on ${{ matrix.node-version }}
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: cd auth && npm i && npm run build && aws s3 sync ./build s3://${{ secrets.ARTIFACTS_BUCKET }}/${{ github.repository }}/${{ github.sha }}/auth
      - run: cd stations && npm i && npm run build && aws s3 sync ./build s3://${{ secrets.ARTIFACTS_BUCKET }}/${{ github.repository }}/${{ github.sha }}/stations